### PR TITLE
Add support for uWSGI

### PR DESCRIPTION
**Pull request by razvand**
Add scripts and configuration files to ease up deployment of WoUSO using uWSGI.

Documentation on using these scripts and configuration files is on the wiki: https://github.com/rosedu/wouso/wiki/WSGI-Support-in-wouso

### CODE REVIEW

**Comment by iulianR** [comment]
@alexef Have a look

**Comment by alexef** [comment]
I have no experience with uwsgi; the configuration looks ok.

I'm using `gunicorn` and `supervisor` in my django production systems, you should keep supervisor in mind as a replacement to homemade start/stop scripts.

**Comment by razvand** [comment]
OK, we'll have that in mind. Until then, let's use the scripts above.

**Comment by razvand** [comment]
@iulianR , please also check the wiki page and see whether the setup works and if any other description is required.

**Pull request merged**
